Refactor cleanup-text to figure out transforms before applying

diff --git a/bin/cleanup-text b/bin/cleanup-text
--- a/bin/cleanup-text
+++ b/bin/cleanup-text
@@ -5,203 +5,154 @@ set -e -u -o pipefail
 CMD="$(basename $0)"
 CMD_DIR="$(dirname $0)"
 function usage {
-    echo "Usage: $CMD [-hnrv]" 1>&2
+    echo "Usage: $CMD [-hnrv] file..." 1>&2
     echo "-h        Print this help message." 1>&2
     echo "-n        Dry run. Don't execute commands." 1>&2
-    echo "-r        Raw text; no special character processing at all (default)." 1>&2
-    echo "-b        Basic character processing." 1>&2
-    echo "          Clean up CRLF, 'safe' 0xFF2D -> + and ^L, ^Z." 1>&2
-    echo "-u        Full Unicode character processing." 1>&2
     echo "-v        Verbose. Print extra information if appropriate." 1>&2
     echo "Filter to clean up J3 paper .txt files." 1>&2
-    echo "Convert to UNIX line endings." 1>&2
+    echo "Convert CRLF, CR line endings to UNIX line endings." 1>&2
     echo "Convert '<FF>2D' to '-'." 1>&2
     echo "Convert odd ^R, ^S, ^T to proper apostrophe and quote characters." 1>&2
     echo "Convert extended ASCII characters to quoting characters." 1>&2
     echo "Convert non-ASCII box-drawing characters to |' -' +." 1>&2
-    # echo "Leave extended ASCII characters as they are (don't use Unicode)." 1>&2
+    echo "Convert extended ASCII to UTF-8." 1>&2
     echo "Remove NUL, ^Z." 1>&2
 }
 
-TMP="$(mktemp "/tmp/$CMD.XXXXXX")"
+. "$CMD_DIR"/vecho
 
-trap "rm -f '$TMP'; exit 1" HUP INT QUIT TERM ERR
-
-# File years/1997/97-149.txt seems to have DOS encoding for
-# umlauted characters. Special char must be taken to
-# only change for names, as there are many other
-# files that use \x94 as a quote character.
-# So, CLEAN_DOS should come before most other changes.
-
-# In the settings below, if a variable is set and
-# a similar line is commented out, the first line
-# is used to fix up ASCII 0x80-0xFF. The second line tries
-# to leave those characters as they found them.
-# But that doesn't seem to work well with modern editors.
-CLEAN_DOS1="-e s/Z\x81rn/Zürn/ -e s/M\x84h\x94nen/Mähönen/"
-
-CLEAN_DOS2="-e s/H\x94gskolan/Högskolan/ -e s/\x99sterman/Österman/"
-
-CLEAN_DOS3="-e s/Trollh\x84ttan/Trollhättan/ -e s/TROLLH\x8ETTAN/TROLLHÄTTAN/"
-
-#                  ^+            +$
-# CLEAN_BOX1="-e 2,\$s/^\xc3/+/ -e s/\xb4\$/+/"
-CLEAN_BOX1=
-
-#                      |   +   +   -   +   +   -   -   +   +   +
-# CLEAN_BOX2="-e 2,\$y/\xb3\xb4\xbf\xc0\xc1\xc2\xc3\xc4\xc5\xd9\xda/|-++++--+++/"
-CLEAN_BOX2=
-
-CLEAN_NUL="-e s/\x00//g"
-CLEAN_CRLF="-e s/\x0d\$//"
-CLEAN_TRAILING_FF="-e \$s/\x0C//"
-CLEAN_TRAILING_SP="-e s/\x20*\$//"
-CLEAN_CTRL_ST="-e s/\x13/“/g -e s/\x14/”/g"
-CLEAN_CTRL_Z="-e \$s/\x1A//g"
-
-CLEAN_ELLIPSES="-e s/\x85/…/g"
-CLEAN_9192="-e s/\x91/\x27/g -e s/\x92/’/g"
-CLEAN_9394="-e s/\x93([[:print:]])/“\1/g -e s/([[:print:]])\x94/\1”/g"
-CLEAN_BULLET1="-e s/\x95/•/g"
-CLEAN_N_DASH="-e s/\x96/–/g"
-CLEAN_NBSP="-e s/\xA0/\x20/g"
-CLEAN_A1BF="-e s/\xA1/¡/g -e s/\xBF/¿/g"
-CLEAN_WP_LESS_EQ="-e s/\xA3/≤/g"
-CLEAN_SECTION="-e s/\xA7/§/g"
-CLEAN_COPYRIGHT="-e s/\xA9/©/g"
-CLEAN_R_GUILLEMET="-e s/\xAB//g"
-CLEAN_SOFT_HYPHEN="-e s/\xAD/-/g"
-CLEAN_PLUS_MINUS1="-e s/\xB1/±/g"
-CLEAN_PARAGRAPH="-e s/\xB6/¶/g"
-CLEAN_BULLET2="-e s/\xB7/•/g"
-CLEAN_E_ACUTE="-e s/\xC9/É/g"
-CLEAN_D5_APOSTROPHE="-e s/\xD5/'/g"
-CLEAN_DADB="-e s/\xDA/'/g -e s/\xDB/'/g"
-CLEAN_C_CEDILLA="-e s/\xE7/ç/g"
-CLEAN_PLUS_MINUS2="-e s/\xF1/±/g"
-
-CLEAN_HEX_FF2D="-e s/\xFF2D/+/g"
-
-CHAR_PROC="-r"
 DRY_RUN=
 ECHO=
-VFLAG=
-while getopts bhnruv\? OPTCHAR; do
+VFLAG=0
+while getopts hnv\? OPTCHAR; do
     case $OPTCHAR in
-        b)  CHAR_PROC="-b";;
         h)  usage; exit 0;;
         n)  DRY_RUN=1 ECHO=echo;;
-        r)  CHAR_PROC="-r";;
-        u)  CHAR_PROC="-u";;
-        v)  VFLAG=1;;
+        v)  VFLAG=$((VFLAG+1));;
     esac
 done
 
 shift $(($OPTIND - 1))
 
 case $# in
-    0)  ;;
-    *)  usage; exit 1;;
+    0)  usage; exit 1;;
+    *)  ;;
 esac
 
-# "sed -e :a -e '/^\n*$/{$d;N;ba' -e '}'" is an idiom
-# for deleting trailing blank lines.
+for F in "$@"; do
+    if [[ ! -f "$F" ]]; then
+        echo "$CMD: '$F': file not found." 1>&2
+        continue
+    fi
 
-# Pass 1: Do all the common transformations for raw and non-raw.
-export LC_ALL=C
-if [[ "$CHAR_PROC" = "-r" ]]; then
-    cat
-elif [[ "$CHAR_PROC" = "-b" ]]; then
-    tr -d '\000' \
-    | sed -E $CLEAN_CRLF \
-        $CLEAN_NUL \
-        $CLEAN_TRAILING_FF \
-        $CLEAN_TRAILING_SP \
-        $CLEAN_CTRL_Z \
-        $CLEAN_HEX_FF2D \
-    | tr '\r' '\n' \
-    | sed -e :a -e '/^\n*$/{$d;N;ba' -e '}'
-elif [[ "$CHAR_PROC" = "-u" ]]; then
-    tr -d '\000' \
-    | sed -E $CLEAN_CRLF \
-        $CLEAN_NUL \
-        $CLEAN_TRAILING_FF \
-        $CLEAN_TRAILING_SP \
-        $CLEAN_CTRL_Z \
-        $CLEAN_HEX_FF2D \
-    | tr '\r' '\n' \
-    | sed -e :a -e '/^\n*$/{$d;N;ba' -e '}' >"$TMP"
+    # Think harder about this, as there is some cleanup
+    # (trailing blank lines, whitespace at end of line)
+    # that we want to do even if the file is ASCII or
+    # Unicode UTF-8.
 
-    case "$(file "$TMP")" in
-        Unicode\ text.*UTF-8*)
-            # Already OK, as already Unicode and UTF-8
-        ;;
-        *)
-    esac
 
-    NON_ASCII="$("$CMD_DIR/non-ascii-histo" "$TMP")"
+    # Examine the file for all the possible transformations
+    # we are able to apply. The transformation names are
+    # the same as the commands in the 'bin' directory
+    # that perform the transformation.
+    TRANSFORMS=$(LC_ALL=C gawk '
+                      BEGIN {
+                          ALL_TRANSFORMS = "";
+                          LAST_LINE_WAS_BLANK = 0;
+                      }
+                      function add_transform(trans) {
+                          if (ALL_TRANSFORMS !~ " " trans) {
+                              ALL_TRANSFORMS = ALL_TRANSFORMS " " trans
+                              vecho 1 "Add " trans
+                          }
+                      }
+                      # Note that the order matters here.
+                      # It is safest to
+                      #    - delete things
+                      #    - do ASCII-to-ASCII transformations
+                      #    - do non-ASCII-to-ASCII transformations
+                      #    - carefully do the non-ASCII-to-UTF-8 transformations.
+                      # This is because some of the UTF-8 encodings
+                      # contain what might be considered non-ISO extended
+                      # ASCII characters.
+                      # (This might be better handled in the conversion
+                      # routines, but that did not work at first try.
 
-    case "$NON_ASCII" in
-        *x01*x02*x04*x05*)    # min-124.txt is trash
-            echo "This file needs to be cleaned up manually" 1>&2
-            exit 1;;
+                      /\x1A/ { add_transform("delete-control-Z") }
+                      /\x81/ { add_transform("delete-x81") }
+                      /\xAB/ { add_transform("delete-8859-xAB") }
+                      NR == 1 && /^\xFE\xFF|^\xEF\xBB\xFF/ {
+                          add_transform("delete-byte-order-marks");
+                      }
 
-        *xb3*xb4*xc3*xc4*)
-            sed -E $CLEAN_BOX1 $CLEAN_BOX2 \
-                $CLEAN_CTRL_ST \
-                $CLEAN_DOS1 \
-                $CLEAN_DOS2 \
-                $CLEAN_DOS3 \
-                $CLEAN_ELLIPSES \
-                $CLEAN_BULLET1 \
-                $CLEAN_N_DASH \
-                $CLEAN_9192 \
-                $CLEAN_9394 \
-                $CLEAN_NBSP \
-                $CLEAN_A1BF \
-                $CLEAN_SECTION \
-                $CLEAN_COPYRIGHT \
-                $CLEAN_R_GUILLEMET \
-                $CLEAN_SOFT_HYPHEN \
-                $CLEAN_PLUS_MINUS1 \
-                $CLEAN_PARAGRAPH \
-                $CLEAN_BULLET2 \
-                $CLEAN_E_ACUTE \
-                $CLEAN_D5_APOSTROPHE \
-                $CLEAN_DADB \
-                $CLEAN_C_CEDILLA \
-                $CLEAN_PLUS_MINUS2 \
-                <"$TMP" ;;
-        *)
-            sed -E \
-                $CLEAN_CTRL_ST \
-                $CLEAN_DOS1 \
-                $CLEAN_DOS2 \
-                $CLEAN_DOS3 \
-                $CLEAN_ELLIPSES \
-                $CLEAN_BULLET1 \
-                $CLEAN_N_DASH \
-                $CLEAN_9192 \
-                $CLEAN_9394 \
-                $CLEAN_NBSP \
-                $CLEAN_A1BF \
-                $CLEAN_SECTION \
-                $CLEAN_COPYRIGHT \
-                $CLEAN_R_GUILLEMET \
-                $CLEAN_SOFT_HYPHEN \
-                $CLEAN_PLUS_MINUS1 \
-                $CLEAN_PARAGRAPH \
-                $CLEAN_BULLET2 \
-                $CLEAN_E_ACUTE \
-                $CLEAN_D5_APOSTROPHE \
-                $CLEAN_DADB \
-                $CLEAN_C_CEDILLA \
-                $CLEAN_PLUS_MINUS2 \
-                < "$TMP";;
-    esac
-    rm -f "$TMP"
-    exit 0
-else
-    echo "$CMD: Can't happen: \$CHAR_PROC = '$CHAR_PROC'" 1>&2
-    exit 1
-fi
+                      /\r./ { add_transform("convert-CR-to-LF") }
+                      /\r$/ { add_transform("convert-CRLF-to-LF") }
+                      /[ \t]\r*$/ { add_transform("delete-whitespace-at-eol") }
+                      /\xFF[2]D/ { add_transform("convert-FF2D-to-plus") }
+                      /\xB3|\xB4|\xC0|\xC1\|\xC2|\xC3\|\xC4|\xC5|\xD9|\xDA/ {
+                          # Omit \xBF in pattern, as overlaps below.
+                          add_transform("convert-xb3-xb4-xbf-etc-to-box-drowing")
+                      }
+
+                      /\xA1/ {
+                          add_transform("convert-8859-xA1-to-inverted-exclamation-mark");
+                      }
+                      /\xA7/ { add_transform("convert-8859-xA7-to-section-mark") }
+                      /\xA9/ { add_transform("convert-8859-xA9-to-copyright-mark") }
+                      /\xAD/ { add_transform("convert-8859-xAD-to-en-dash") }
+                      /\xB1/ { add_transform("convert-8859-xB1-to-plus-minus") }
+
+                      /\xB7/ { add_transform("convert-8859-xB7-to-bullet") }
+                      /\xBF/ {
+                          if (ALL_TRANSFORMS !~ "convert-xb3-xb4-xbf-etc-to-box-drowing") {
+                              # There is overlap with box-drowing in 96-115r3.txt
+                              add_transform("convert-8859-xBF-to-inverted-question-mark")
+                          }
+                      }
+                      /\xC9/ { add_transform("convert-8859-xC9-to-ellipsis") }
+                      /\xD3/ { add_transform("convert-8859-xD2-xD3-to-curly-quotes") }
+                      /\xD5/ { add_transform("convert-8859-xD5-to-apostrophe") }
+                      /\xE7/ { add_transform("convert-8859-xE7-to-c-cedilla") }
+                      /\xF1/ { add_transform("convert-8859-xF1-to-less-than-or-equal") }
+                      /\x85/ { add_transform("convert-NEL-to-ellipses") }
+                      /\x94/ { add_transform("convert-x91-x94-to-curly-quotes") }
+                      /\x96/ { add_transform("convert-x96-to-en-dash") }
+                      /\x97/ { add_transform("convert-x97-to-em-dash") }
+                      /\xA0/ { add_transform("convert-xA0-to-non-breaking-space") }
+                      /\xA3/ { add_transform("convert-xA3-to-less-than-or-equal") }
+                      /\xB6/ { add_transform("convert-xB6-to-paragraph-mark") }
+                      /\xE9|\xEB|\xF9|\xFB/ {
+                          add_transform("convert-xE9_xEB-xF9-xFB-to-matrix-corners");
+                      }
+                      /^[ \t]*\r*$/ { LAST_LINE_WAS_BLANK = 1 }
+                      /[^ \t\r]/  { LAST_LINE_WAS_BLANK = 0 }
+                      END {
+                          if (LAST_LINE_WAS_BLANK)
+                              add_transform("delete-trailing-blank-lines");
+                           if (ALL_TRANSFORMS != "")
+                               print substr(ALL_TRANSFORMS, 2);
+                      }' \
+                 "$F")
+
+    vecho 1 "Transformations for \"$F\": $TRANSFORMS"
+
+    if [[ "$TRANSFORMS" == "" ]]; then
+        vecho 1 "Nothing in \"$F\" to transform"
+        continue
+    fi
+
+    CB="bin"
+    CB="../gg-j3-papers/bin"
+    PIPELINE="$(echo "$TRANSFORMS" | sed -e "s;^;$CB/;" -e "s; ; | $CB/;g")"
+    vecho 1 "PIPELINE=$PIPELINE"
+
+    if [[ -z "$DRY_RUN" ]]; then
+        vecho 1 "chmod +w \"$F\"; cat \"$F\" | eval \"$PIPELINE\" | cpif \"$F\"; chmod -w \"$F\""
+        chmod +w "$F"
+        (export LC_ALL=C; cat "$F" | eval "$PIPELINE" | cpif "$F")
+        chmod -w "$F"
+        vecho 1 "$(file "$F")"
+    fi
+done
+
+exit 0
