Add Zettelkasten id, and just do one at a time

diff --git a/bin/create-paper-note b/bin/create-paper-note
--- a/bin/create-paper-note
+++ b/bin/create-paper-note
@@ -6,12 +6,13 @@ set -u -o pipefail
 
 CMD="$(basename $0)"
 function usage {
-    echo "Usage: $CMD [-hnv] ..." 1>&2
+    echo "Usage: $CMD [-hnv] j3-paper-number zk-id" 1>&2
     echo "-h        Print this help message." 1>&2
     echo "-n        Dry run. Don't execute commands." 1>&2
     echo "-o        Open the new file when created." 1>&2
     echo "-t        Print org-mode style TODO for the entry." 1>&2
     echo "-v        Verbose. Print extra information if appropriate." 1>&2
+    echo "Create a J3 paper note for j3-paper-number with Zettelkasten zk-id." 1>&2
 }
 
 . $(dirname "$0")/vecho
@@ -19,7 +20,7 @@ function usage {
 DRY_RUN=
 ECHO=
 OFLAG=
-TFLAG=
+TFLAG=1
 VFLAG=
 while getopts hnotv\? OPTCHAR; do
     case $OPTCHAR in
@@ -34,8 +35,8 @@ done
 shift $(($OPTIND - 1))
 
 case $# in
-    0)  usage; exit 1;;
-    *)  ;;
+    2)  PAPER_ID="$1" ZK_ID="$2";;
+    *)  usage; exit 1;;
 esac
 
 if [[ ! -d "papers" ]]; then
@@ -44,57 +45,54 @@ if [[ ! -d "papers" ]]; then
 fi
 
 
-for P in "$@"; do
-    PAPER_MATCHES="$(builtin cd papers && /bin/ls *"$P"* 2>/dev/null)"
-    vecho 1 "Matches: $PAPER_MATCHES"
-    if [[ "$PAPER_MATCHES" =~ "*" ]] || [[ "$PAPER_MATCHES" = "" ]]; then
-        echo "$CMD: No match for '$P'" 1>&2
-        continue
-    fi
+PAPER_MATCHES="$(builtin cd papers && /bin/ls *"$PAPER_ID"* 2>/dev/null)"
+vecho 1 "Matches: $PAPER_MATCHES"
+if [[ "$PAPER_MATCHES" =~ "*" ]] || [[ "$PAPER_MATCHES" = "" ]]; then
+    echo "$CMD: No match for '$P'" 1>&2
+    continue
+fi
 
-    BASE_NAME="$(echo "$PAPER_MATCHES" | sed -n -e 's/r[0-9]*\././' -e '1s/\.[^.]*//p')"
-    vecho 1 "  BASE_NAME='$BASE_NAME'"
+BASE_NAME="$(echo "$PAPER_MATCHES" | sed -n -e 's/r[0-9]*\././' -e '1s/\.[^.]*//p')"
+vecho 1 "  BASE_NAME='$BASE_NAME'"
 
-    if [[ -f "$BASE_NAME.txt" ]]; then
-        PREFERRED_SUFFIX=txt
-    elif [[ -f "$BASE_NAME.pdf" ]]; then
-        PREFERRED_SUFFIX=pdf
-    else
-        PREFERRED_SUFFIX=txt
-    fi
-    vecho 1 "  PREFERRED_SUFFIX='$PREFERRED_SUFFIX'"
+if [[ -f "$BASE_NAME.txt" ]]; then
+    PREFERRED_SUFFIX=txt
+elif [[ -f "$BASE_NAME.pdf" ]]; then
+    PREFERRED_SUFFIX=pdf
+else
+    PREFERRED_SUFFIX=txt
+fi
+vecho 1 "  PREFERRED_SUFFIX='$PREFERRED_SUFFIX'"
 
+MEETING="$(ls meetings/*/"$BASE_NAME".* 2>/dev/null | sed -n -e '1s;.*/\(.*\)/.*;\1;p')"
+vecho 1 "  MEETING='$MEETING'"
 
-    MEETING="$(ls meetings/*/"$BASE_NAME".* 2>/dev/null | sed -n -e '1s;.*/\(.*\)/.*;\1;p')"
-    vecho 1 "  MEETING='$MEETING'"
+if [[ "$MEETING" =~ "*" ]]; then
+    echo "$CMD: Can't identify meeting number for '$PAPER'" 1>&2
+    continue
+fi
 
-    if [[ "$MEETING" =~ "*" ]]; then
-        echo "$CMD: Can't identify meeting number for '$PAPER'" 1>&2
-        continue
-    fi
+if [[ "$PREFERRED_SUFFIX" = "txt" ]]; then
+    SUBJECT="$(grep Subject: papers/$BASE_NAME.txt | sed -e 's/Subject:  *//' -e 's/  *$//' -e 's;[/:][/:]*;-;g')"
+else
+    SUBJECT=
+fi
+vecho 1 "  SUBJECT='$SUBJECT'"
 
+if [[ "$SUBJECT" = "" ]]; then
+    ZK_FILE="$ZK_ID J3 #$MEETING Paper $BASE_NAME.org"
+else
+    ZK_FILE="$ZK_ID J3 #$MEETING Paper $BASE_NAME $SUBJECT.org"
+fi
 
-    if [[ "$PREFERRED_SUFFIX" = "txt" ]]; then
-        SUBJECT="$(grep Subject: papers/$BASE_NAME.txt | sed -e 's/Subject:  *//' -e 's/  *$//' -e 's;[/:][/:]*;-;g')"
-    else
-        SUBJECT=
-    fi
-    vecho 1 "  SUBJECT='$SUBJECT'"
+if [[ -e ~/Documents/ZK/"$ZK_FILE" ]]; then
+    echo "$ZK_FILE already exists"
+    UUID="$(sed -n -e 's/^:[Ii][Dd]: *//p' ~/Documents/ZK/"$ZK_FILE" | head -1)"
+else
+    UUID="$(uuidgen)"
 
-    if [[ "$SUBJECT" = "" ]]; then
-        ZK_FILE="J3 #$MEETING Paper $BASE_NAME.org"
-    else
-        ZK_FILE="J3 #$MEETING Paper $BASE_NAME $SUBJECT.org"
-    fi
-
-    if [[ -e ~/Documents/ZK/"$ZK_FILE" ]]; then
-        echo "$ZK_FILE already exists"
-        UUID="$(sed -n -e 's/^:[Ii][Dd]: *//p' ~/Documents/ZK/"$ZK_FILE" | head -1)"
-    else
-        UUID="$(uuidgen)"
-
-        TEXT="$(echo ":PROPERTIES:
-:ID:       $UUID
+    TEXT="$(echo ":PROPERTIES:
+:ID:                    $UUID
 :END:
 #+title: ${ZK_FILE/.org}
 #+date: [$(date '+%F %a %H:%M')]
@@ -115,19 +113,18 @@ $(echo "$PAPER_MATCHES" | sed -e "s/\(.*\)\(r.*\)*\.*/- [[j3-paper:&][\1\2 $SUBJ
 
 * Links")"
 
-        if [[ -n "$DRY_RUN" ]]; then
-            echo "echo \"$TEXT\" >\"~/Documents/ZK/$ZK_FILE\""
-        else
-            echo "$TEXT" >~/Documents/ZK/"$ZK_FILE"
-        fi
-
+    if [[ -n "$DRY_RUN" ]]; then
+        echo "echo \"$TEXT\" >\"~/Documents/ZK/$ZK_FILE\""
+    else
+        echo "$TEXT" >~/Documents/ZK/"$ZK_FILE"
     fi
 
-    echo "[[id:$UUID][$(basename "$ZK_FILE" .org)]]"
+fi
 
-    if [[ -n "$OFLAG" ]]; then
-        $ECHO open "$ZK_FILE"
-    fi
-done
+echo "[[id:$UUID][$(basename "$ZK_FILE" .org)]]"
+
+if [[ -n "$OFLAG" ]]; then
+    $ECHO open "$ZK_FILE"
+fi
 
 $ECHO emacsclient -e "(when (fboundp 'org-roam-update-org-id-locations) (org-roam-update-org-id-locations))"
